Repository breqwatr/voithos, pull requests merged in 2022-04, with the labels that each got.

#138 [BREQ 1855] Ceph configs globals file
  docs/openstack-kolla-globals.md
Labels: minor-fix

#139 [BREQ 1863] Add links argument in integration create command
  voithos/cli/service/arcus/integrations.py
  voithos/lib/service/arcus/integrations.py
Labels: minor-change

#140 updated docs for ceph nova username requirement after Victoria release
  docs/openstack-kolla-globals.md
Labels: documentation
